nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
enableGlobalCache: true
enableScripts: true
enableStrictSsl: true
enableTelemetry: false
yarnPath: .yarn/releases/yarn-4.8.1.cjs 