nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
enableGlobalCache: true
enableScripts: true
enableStrictSsl: true
enableTelemetry: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-4.8.1.cjs 