name: Branch Protection

on:
  pull_request:
    branches: [ main, develop, test/branch-protection ]
  push:
    branches: [ main, develop, test/branch-protection ]

jobs:
  branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        working-directory: packages/shared
        run: yarn test

      - name: Run linting
        working-directory: packages/shared
        run: yarn lint

      - name: Check branch protection
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const { data: branch } = await github.rest.repos.getBranch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: context.payload.pull_request?.base?.ref || context.ref.replace('refs/heads/', '')
              });

              if (!branch.protected) {
                console.log('Warning: Branch is not protected. Protection rules should be enabled.');
                return;
              }

              const { data: protection } = await github.rest.repos.getBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: context.payload.pull_request?.base?.ref || context.ref.replace('refs/heads/', '')
              });

              console.log('Branch protection rules found:', protection);
            } catch (error) {
              if (error.status === 404) {
                console.log('Branch protection not configured yet. This is expected for new branches.');
                return;
              }
              throw error;
            } 