name: Documentation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'packages/shared/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: 'packages/shared/package-lock.json'

    - name: Install Dependencies
      run: |
        cd packages/shared
        npm ci

    - name: Build Documentation
      run: |
        cd packages/shared
        npm run docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: packages/shared/docs
        publish_branch: gh-pages
        destination_dir: shared 