name: Test

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'packages/shared/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'packages/shared/**'
      - '.github/workflows/test.yml'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    
    - name: Install Dependencies
      run: |
        yarn set version classic
        yarn install --frozen-lockfile

    - name: Run Lint
      working-directory: packages/shared
      run: yarn lint

    - name: Run Tests
      working-directory: packages/shared
      run: yarn test
      env:
        NODE_ENV: test

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-${{ matrix.node-version }}
        path: packages/shared/coverage/
        retention-days: 7 