name: Test

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'packages/shared/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'packages/shared/**'
      - '.github/workflows/test.yml'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Dependencies
      run: |
        npm install -g yarn
        yarn install

    - name: Run Lint
      run: yarn workspace shared lint

    - name: Run Tests
      run: yarn workspace shared test

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-${{ matrix.node-version }}
        path: packages/shared/coverage/
        retention-days: 7 